// This file is automatically generated. Do not edit directly. 
export const themes = [
  {
    "type": "dark",
    "value": "Onemm-themes-1mm-themes-dark-plus",
    "label": "1mm Themes-1mm Themes Dark Plus (dark)"
  },
  {
    "type": "dark",
    "value": "Onemm-themes-1mm-themes-dracula",
    "label": "1mm Themes-1mm Themes Dracula (dark)"
  },
  {
    "type": "dark",
    "value": "Onemm-themes-1mm-themes-monokai",
    "label": "1mm Themes-1mm Themes Monokai (dark)"
  },
  {
    "type": "dark",
    "value": "Onemm-themes-1mm-themes-one-dark-pro",
    "label": "1mm Themes-1mm Themes One Dark Pro (dark)"
  },
  {
    "type": "dark",
    "value": "Two077-theme-2077-theme-color-theme",
    "label": "2077 Theme-2077 Theme Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "Eightbit-dark-color-theme",
    "label": "8bit Dark Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "Eightbit-light-color-theme",
    "label": "8bit Light Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "a-touch-of-lilac-theme-a-touch-of-lilac-no-italics",
    "label": "A Touch Of Lilac Theme A Touch Of Lilac No Italics (dark)"
  },
  {
    "type": "dark",
    "value": "a-touch-of-lilac-theme-a-touch-of-lilac",
    "label": "A Touch Of Lilac Theme A Touch Of Lilac (dark)"
  },
  {
    "type": "dark",
    "value": "after-dark-After-Dark-color-theme",
    "label": "After Dark-After-Dark Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "alek-kai-theme-alekKai",
    "label": "Alek Kai Theme AlekKai (light)"
  },
  {
    "type": "light",
    "value": "alek-kai-theme-alekKaiSat",
    "label": "Alek Kai Theme AlekKaiSat (light)"
  },
  {
    "type": "dark",
    "value": "amethyst-theme-amethyst-color-theme",
    "label": "Amethyst Theme Amethyst Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "amethyst-theme-amethyst-dark-color-theme",
    "label": "Amethyst Theme Amethyst Dark Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "amethyst-theme-amethyst-light-color-theme",
    "label": "Amethyst Theme Amethyst Light Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "august-themes-august-ariake-dark",
    "label": "August Themes August Ariake Dark (dark)"
  },
  {
    "type": "dark",
    "value": "august-themes-august-drawbridge-darker",
    "label": "August Themes August Drawbridge Darker (dark)"
  },
  {
    "type": "dark",
    "value": "august-themes-august-drawbridge",
    "label": "August Themes August Drawbridge (dark)"
  },
  {
    "type": "dark",
    "value": "august-themes-august-night-owl-darker",
    "label": "August Themes August Night Owl Darker (dark)"
  },
  {
    "type": "dark",
    "value": "august-themes-august-night-owl",
    "label": "August Themes August Night Owl (dark)"
  },
  {
    "type": "dark",
    "value": "august-themes-august-radical-2",
    "label": "August Themes August Radical-2 (dark)"
  },
  {
    "type": "dark",
    "value": "august-themes-august-radical",
    "label": "August Themes August Radical (dark)"
  },
  {
    "type": "dark",
    "value": "ayu-adaptive-ayu-adapta",
    "label": "Ayu Adaptive Ayu Adapta (dark)"
  },
  {
    "type": "dark",
    "value": "ayu-adaptive-ayu-mojave",
    "label": "Ayu Adaptive Ayu Mojave (dark)"
  },
  {
    "type": "dark",
    "value": "ayu-adaptive-ayu-one",
    "label": "Ayu Adaptive Ayu One (dark)"
  },
  {
    "type": "dark",
    "value": "ayu-ayu-dark-bordered",
    "label": "Ayu Ayu Dark Bordered (dark)"
  },
  {
    "type": "dark",
    "value": "ayu-ayu-dark",
    "label": "Ayu Ayu Dark (dark)"
  },
  {
    "type": "light",
    "value": "ayu-ayu-light-bordered",
    "label": "Ayu Ayu Light Bordered (light)"
  },
  {
    "type": "light",
    "value": "ayu-ayu-light",
    "label": "Ayu Ayu Light (light)"
  },
  {
    "type": "dark",
    "value": "ayu-ayu-mirage-bordered",
    "label": "Ayu Ayu Mirage Bordered (dark)"
  },
  {
    "type": "dark",
    "value": "ayu-ayu-mirage",
    "label": "Ayu Ayu Mirage (dark)"
  },
  {
    "type": "dark",
    "value": "ayu-miragemod-Ayu-Mirage-Mod-color-theme",
    "label": "Ayu Miragemod-Ayu-Mirage-Mod Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "ayu-one-dark-ayu-one-dark",
    "label": "Ayu One Dark Ayu One Dark (dark)"
  },
  {
    "type": "dark",
    "value": "ayu-one-dark-pro-ayu-one-dark-pro-dark-bordered-color-theme",
    "label": "Ayu One Dark Pro Ayu One Dark Pro Dark Bordered Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "ayu-one-dark-pro-ayu-one-dark-pro-dark-color-theme",
    "label": "Ayu One Dark Pro Ayu One Dark Pro Dark Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "ayu-one-dark-pro-ayu-one-dark-pro-mirage-bordered-color-theme",
    "label": "Ayu One Dark Pro Ayu One Dark Pro Mirage Bordered Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "ayu-one-dark-pro-ayu-one-dark-pro-mirage-color-theme",
    "label": "Ayu One Dark Pro Ayu One Dark Pro Mirage Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "ballerini-theme-ballerini-theme",
    "label": "Ballerini Theme Ballerini Theme (dark)"
  },
  {
    "value": "beardedtheme-bearded-theme-arc-blueberry",
    "label": "Beardedtheme Bearded Theme Arc Blueberry (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-arc-eggplant",
    "label": "Beardedtheme Bearded Theme Arc Eggplant (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-arc-eolstorm",
    "label": "Beardedtheme Bearded Theme Arc Eolstorm (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-arc-reversed",
    "label": "Beardedtheme Bearded Theme Arc Reversed (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-arc",
    "label": "Beardedtheme Bearded Theme Arc (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-black-amethyst",
    "label": "Beardedtheme Bearded Theme Black Amethyst (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-black-diamond",
    "label": "Beardedtheme Bearded Theme Black Diamond (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-black-emerald",
    "label": "Beardedtheme Bearded Theme Black Emerald (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-black-gold",
    "label": "Beardedtheme Bearded Theme Black Gold (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-black-ruby",
    "label": "Beardedtheme Bearded Theme Black Ruby (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-classics-anthracite",
    "label": "Beardedtheme Bearded Theme Classics Anthracite (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-classics-light",
    "label": "Beardedtheme Bearded Theme Classics Light (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-coffee-cream",
    "label": "Beardedtheme Bearded Theme Coffee Cream (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-coffee-reversed",
    "label": "Beardedtheme Bearded Theme Coffee Reversed (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-coffee",
    "label": "Beardedtheme Bearded Theme Coffee (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-exotic-altica",
    "label": "Beardedtheme Bearded Theme Exotic Altica (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-exotic-earth",
    "label": "Beardedtheme Bearded Theme Exotic Earth (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-exotic-void",
    "label": "Beardedtheme Bearded Theme Exotic Void (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-hc-brewing-storm",
    "label": "Beardedtheme Bearded Theme Hc Brewing Storm (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-hc-chocolateespresso",
    "label": "Beardedtheme Bearded Theme Hc Chocolateespresso (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-hc-ebony",
    "label": "Beardedtheme Bearded Theme Hc Ebony (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-hc-flurry",
    "label": "Beardedtheme Bearded Theme Hc Flurry (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-hc-midnightvoid",
    "label": "Beardedtheme Bearded Theme Hc Midnightvoid (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-hc-minuit",
    "label": "Beardedtheme Bearded Theme Hc Minuit (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-hc-wonderland-wood",
    "label": "Beardedtheme Bearded Theme Hc Wonderland Wood (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-monokai-black",
    "label": "Beardedtheme Bearded Theme Monokai Black (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-monokai-metallian",
    "label": "Beardedtheme Bearded Theme Monokai Metallian (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-monokai-reversed",
    "label": "Beardedtheme Bearded Theme Monokai Reversed (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-monokai-stone",
    "label": "Beardedtheme Bearded Theme Monokai Stone (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-monokai-terra",
    "label": "Beardedtheme Bearded Theme Monokai Terra (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-oceanic-reversed",
    "label": "Beardedtheme Bearded Theme Oceanic Reversed (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-oceanic",
    "label": "Beardedtheme Bearded Theme Oceanic (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-solarized-dark",
    "label": "Beardedtheme Bearded Theme Solarized Dark (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-solarized-light",
    "label": "Beardedtheme Bearded Theme Solarized Light (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-solarized-reversed",
    "label": "Beardedtheme Bearded Theme Solarized Reversed (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-stained-blue",
    "label": "Beardedtheme Bearded Theme Stained Blue (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-stained-purple",
    "label": "Beardedtheme Bearded Theme Stained Purple (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-surprising-blueberry",
    "label": "Beardedtheme Bearded Theme Surprising Blueberry (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-surprising-eggplant",
    "label": "Beardedtheme Bearded Theme Surprising Eggplant (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-surprising-watermelon",
    "label": "Beardedtheme Bearded Theme Surprising Watermelon (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-vivid-black",
    "label": "Beardedtheme Bearded Theme Vivid Black (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-vivid-light",
    "label": "Beardedtheme Bearded Theme Vivid Light (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-vivid-purple",
    "label": "Beardedtheme Bearded Theme Vivid Purple (undefined)"
  },
  {
    "value": "beardedtheme-bearded-theme-will",
    "label": "Beardedtheme Bearded Theme Will (undefined)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Ayu-Dark-color-theme",
    "label": "Beautiful Ui-Ayu-Dark Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "beautiful-ui-Ayu-Light-color-theme",
    "label": "Beautiful Ui-Ayu-Light Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Ayu-Mirage-color-theme",
    "label": "Beautiful Ui-Ayu-Mirage Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Eighties-Dark-color-theme",
    "label": "Beautiful Ui-Eighties-Dark Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Espresso-Libre-color-theme",
    "label": "Beautiful Ui-Espresso-Libre Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "beautiful-ui-Espresso-Soda-color-theme",
    "label": "Beautiful Ui-Espresso-Soda Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Material-Darker-color-theme",
    "label": "Beautiful Ui-Material-Darker Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Material-Palenight-color-theme",
    "label": "Beautiful Ui-Material-Palenight Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Material-color-theme",
    "label": "Beautiful Ui-Material Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Minimal-Blue-color-theme",
    "label": "Beautiful Ui-Minimal-Blue Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Minimal-Green-color-theme",
    "label": "Beautiful Ui-Minimal-Green Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Minimal-Purple-color-theme",
    "label": "Beautiful Ui-Minimal-Purple Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Minimal-Yellow-color-theme",
    "label": "Beautiful Ui-Minimal-Yellow Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Monokai-Classic-color-theme",
    "label": "Beautiful Ui-Monokai-Classic Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Monokai-Machine-color-theme",
    "label": "Beautiful Ui-Monokai-Machine Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Monokai-Octagon-color-theme",
    "label": "Beautiful Ui-Monokai-Octagon Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Monokai-Pro-color-theme",
    "label": "Beautiful Ui-Monokai-Pro Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Monokai-Ristretto-color-theme",
    "label": "Beautiful Ui-Monokai-Ristretto Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Monokai-Spectrum-color-theme",
    "label": "Beautiful Ui-Monokai-Spectrum Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Nord-color-theme",
    "label": "Beautiful Ui-Nord Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Nova-color-theme",
    "label": "Beautiful Ui-Nova Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Ocean-Dark-color-theme",
    "label": "Beautiful Ui-Ocean-Dark Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "beautiful-ui-Ocean-Light-color-theme",
    "label": "Beautiful Ui-Ocean-Light Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Oceanic-Next-color-theme",
    "label": "Beautiful Ui-Oceanic-Next Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-One-Dark-color-theme",
    "label": "Beautiful Ui-One-Dark Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "beautiful-ui-One-Light-color-theme",
    "label": "Beautiful Ui-One-Light Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Solarized-Dark-color-theme",
    "label": "Beautiful Ui-Solarized-Dark Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "beautiful-ui-Solarized-Light-color-theme",
    "label": "Beautiful Ui-Solarized-Light Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Tomorrow-Dark-color-theme",
    "label": "Beautiful Ui-Tomorrow-Dark Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "beautiful-ui-Tomorrow-Light-color-theme",
    "label": "Beautiful Ui-Tomorrow-Light Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Tomorrow-Subliminal-color-theme",
    "label": "Beautiful Ui-Tomorrow-Subliminal Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "beautiful-ui-Zenburn-color-theme",
    "label": "Beautiful Ui-Zenburn Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "black-black-italic",
    "label": "Black Black Italic (dark)"
  },
  {
    "type": "dark",
    "value": "black-black",
    "label": "Black Black (dark)"
  },
  {
    "type": "light",
    "value": "blue-light-blue-light-2022-color-theme",
    "label": "Blue Light Blue Light-2022 Color Theme (light)"
  },
  {
    "value": "brackets-light-pro-Brackets-Light-Pro-color-theme-Bold",
    "label": "Brackets Light Pro-Brackets-Light-Pro Color Theme-Bold (undefined)"
  },
  {
    "value": "brackets-light-pro-Brackets-Light-Pro-color-theme",
    "label": "Brackets Light Pro-Brackets-Light-Pro Color Theme (undefined)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-A00",
    "label": "Bunker-Dobri-A00 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-A01",
    "label": "Bunker-Dobri-A01 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-A02",
    "label": "Bunker-Dobri-A02 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-A03",
    "label": "Bunker-Dobri-A03 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-A04",
    "label": "Bunker-Dobri-A04 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-A05",
    "label": "Bunker-Dobri-A05 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-A06",
    "label": "Bunker-Dobri-A06 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-A07",
    "label": "Bunker-Dobri-A07 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-A08",
    "label": "Bunker-Dobri-A08 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-A09",
    "label": "Bunker-Dobri-A09 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-A10",
    "label": "Bunker-Dobri-A10 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-B01",
    "label": "Bunker-Dobri-B01 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-B02",
    "label": "Bunker-Dobri-B02 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-B03",
    "label": "Bunker-Dobri-B03 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-C01",
    "label": "Bunker-Dobri-C01 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-C02",
    "label": "Bunker-Dobri-C02 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-C03",
    "label": "Bunker-Dobri-C03 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-C04",
    "label": "Bunker-Dobri-C04 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-C05",
    "label": "Bunker-Dobri-C05 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-C06",
    "label": "Bunker-Dobri-C06 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-C07",
    "label": "Bunker-Dobri-C07 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-C08",
    "label": "Bunker-Dobri-C08 (dark)"
  },
  {
    "type": "dark",
    "value": "bunker-Dobri-C09",
    "label": "Bunker-Dobri-C09 (dark)"
  },
  {
    "type": "dark",
    "value": "celestial-Celestial-color-theme",
    "label": "Celestial-Celestial Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "chinolor-Chinolor-color-theme",
    "label": "Chinolor-Chinolor Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "chinolor-Chinolor-light-color-theme",
    "label": "Chinolor-Chinolor Light Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "code-blue-code-blue-theme",
    "label": "Code Blue Code Blue Theme (dark)"
  },
  {
    "type": "dark",
    "value": "code-plus-theme-theme-dark-blue-color-theme",
    "label": "Code Plus Theme Theme Dark Blue Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "code-plus-theme-theme-dark-brown-color-theme",
    "label": "Code Plus Theme Theme Dark Brown Color Theme (dark)"
  },
  {
    "value": "codestackr-theme-codeSTACKr-theme-muted",
    "label": "Codestackr Theme CodeSTACKr Theme Muted (undefined)"
  },
  {
    "value": "codestackr-theme-codeSTACKr-theme",
    "label": "Codestackr Theme CodeSTACKr Theme (undefined)"
  },
  {
    "type": "dark",
    "value": "cold-horizon-vscode-cold",
    "label": "Cold Horizon Vscode Cold (dark)"
  },
  {
    "type": "dark",
    "value": "cold-horizon-vscode-normal",
    "label": "Cold Horizon Vscode Normal (dark)"
  },
  {
    "value": "ColdFusion-cfmldark",
    "label": "ColdFusion Cfmldark (undefined)"
  },
  {
    "type": "light",
    "value": "ColdFusion-cfmllight",
    "label": "ColdFusion Cfmllight (light)"
  },
  {
    "type": "dark",
    "value": "copilot-theme-Copilot-Theme-color-theme",
    "label": "Copilot Theme-Copilot-Theme Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "crayon-vscode-crayon",
    "label": "Crayon Vscode Crayon (dark)"
  },
  {
    "type": "dark",
    "value": "cyberpunk-cyberpunk-umbra-color-theme",
    "label": "Cyberpunk Cyberpunk Umbra Color Theme (dark)"
  },
  {
    "value": "dank-neon-Dank-Neon-color-theme-light",
    "label": "Dank Neon-Dank-Neon Color Theme Light (undefined)"
  },
  {
    "type": "dark",
    "value": "dark-horizon-Dark-Horizon-color-theme",
    "label": "Dark Horizon-Dark-Horizon Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "dark-low-contrast-dark-low-contrast-cold-color-theme",
    "label": "Dark Low Contrast Dark Low Contrast Cold Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "dark-low-contrast-dark-low-contrast-color-theme",
    "label": "Dark Low Contrast Dark Low Contrast Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "dark-low-contrast-dark-low-contrast-fire-color-theme",
    "label": "Dark Low Contrast Dark Low Contrast Fire Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "dark-low-contrast-dark-low-contrast-nature-color-theme",
    "label": "Dark Low Contrast Dark Low Contrast Nature Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "dark-low-contrast-dark-low-contrast-warm-color-theme",
    "label": "Dark Low Contrast Dark Low Contrast Warm Color Theme (dark)"
  },
  {
    "value": "dark-plus-material-dark-plus-material",
    "label": "Dark Plus Material Dark Plus Material (undefined)"
  },
  {
    "type": "dark",
    "value": "dark-plus-syntax-dark-plus-syntax-color-theme",
    "label": "Dark Plus Syntax Dark Plus Syntax Color Theme (dark)"
  },
  {
    "type": "hc",
    "value": "dark-plus-syntax-dark-plus-syntax-high-contrast-color-theme",
    "label": "Dark Plus Syntax Dark Plus Syntax High Contrast Color Theme (hc)"
  },
  {
    "type": "light",
    "value": "dark-plus-syntax-light-plus-syntax-color-theme",
    "label": "Dark Plus Syntax Light Plus Syntax Color Theme (light)"
  },
  {
    "type": "hc",
    "value": "dark-plus-syntax-light-plus-syntax-high-contrast-color-theme",
    "label": "Dark Plus Syntax Light Plus Syntax High Contrast Color Theme (hc)"
  },
  {
    "type": "dark",
    "value": "darkpp-italic-Dark-Italic-color-theme",
    "label": "Darkpp Italic-Dark-Italic Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "delphi-themes-delphi-classic-color-theme",
    "label": "Delphi Themes Delphi Classic Color Theme (light)"
  },
  {
    "type": "light",
    "value": "delphi-themes-delphi-default-color-theme",
    "label": "Delphi Themes Delphi Default Color Theme (light)"
  },
  {
    "type": "light",
    "value": "delphi-themes-delphi-ocean-color-theme",
    "label": "Delphi Themes Delphi Ocean Color Theme (light)"
  },
  {
    "type": "light",
    "value": "delphi-themes-delphi-plus-classic-color-theme",
    "label": "Delphi Themes Delphi Plus Classic Color Theme (light)"
  },
  {
    "type": "light",
    "value": "delphi-themes-delphi-plus-ocean-color-theme",
    "label": "Delphi Themes Delphi Plus Ocean Color Theme (light)"
  },
  {
    "type": "light",
    "value": "delphi-themes-delphi-plus-twilight-color-theme",
    "label": "Delphi Themes Delphi Plus Twilight Color Theme (light)"
  },
  {
    "type": "light",
    "value": "delphi-themes-delphi-twilight-color-theme",
    "label": "Delphi Themes Delphi Twilight Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "developer-theme-dark-Aubergine-Dark",
    "label": "Developer Theme Dark-Aubergine-Dark (dark)"
  },
  {
    "type": "dark",
    "value": "developer-theme-dark-Developers-Theme-dark",
    "label": "Developer Theme Dark-Developers-Theme Dark (dark)"
  },
  {
    "type": "dark",
    "value": "developer-theme-dark-Green-coffee",
    "label": "Developer Theme Dark-Green Coffee (dark)"
  },
  {
    "type": "dark",
    "value": "developer-theme-dark-OceanDark",
    "label": "Developer Theme Dark-OceanDark (dark)"
  },
  {
    "type": "dark",
    "value": "dracula-high-contrast-Dracula-new-contrast-no-semantic",
    "label": "Dracula High Contrast-Dracula New Contrast No Semantic (dark)"
  },
  {
    "type": "dark",
    "value": "dracula-high-contrast-Dracula-new-contrast",
    "label": "Dracula High Contrast-Dracula New Contrast (dark)"
  },
  {
    "type": "dark",
    "value": "electron-highlighter-electron-highlighter-color-theme",
    "label": "Electron Highlighter Electron Highlighter Color Theme (dark)"
  },
  {
    "value": "escook-theme-escook-theme-light-soft-color-theme",
    "label": "Escook Theme Escook Theme Light Soft Color Theme (undefined)"
  },
  {
    "type": "dark",
    "value": "firefly-firefly-pro-bright",
    "label": "Firefly Firefly Pro Bright (dark)"
  },
  {
    "type": "dark",
    "value": "firefly-firefly-pro-midnight",
    "label": "Firefly Firefly Pro Midnight (dark)"
  },
  {
    "type": "dark",
    "value": "firefly-firefly-pro",
    "label": "Firefly Firefly Pro (dark)"
  },
  {
    "type": "dark",
    "value": "firefox-quantum-themes-Quantum-Dark",
    "label": "Firefox Quantum Themes-Quantum-Dark (dark)"
  },
  {
    "type": "light",
    "value": "firefox-quantum-themes-Quantum-Light",
    "label": "Firefox Quantum Themes-Quantum-Light (light)"
  },
  {
    "type": "dark",
    "value": "fixthecode-vs-Fixthecode-color-theme",
    "label": "Fixthecode Vs-Fixthecode Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "freecodecamp-dark-vscode-theme-freeCodeCamp-Dark-Theme-color-theme",
    "label": "Freecodecamp Dark Vscode Theme FreeCodeCamp-Dark-Theme Color Theme (dark)"
  },
  {
    "value": "fresh-material-fresh-material-blue",
    "label": "Fresh Material Fresh Material Blue (undefined)"
  },
  {
    "value": "fresh-material-fresh-material-cyan",
    "label": "Fresh Material Fresh Material Cyan (undefined)"
  },
  {
    "value": "fresh-material-fresh-material-green",
    "label": "Fresh Material Fresh Material Green (undefined)"
  },
  {
    "value": "fresh-material-fresh-material-indigo",
    "label": "Fresh Material Fresh Material Indigo (undefined)"
  },
  {
    "value": "fresh-material-fresh-material-pink",
    "label": "Fresh Material Fresh Material Pink (undefined)"
  },
  {
    "value": "fresh-material-fresh-material-red",
    "label": "Fresh Material Fresh Material Red (undefined)"
  },
  {
    "value": "fresh-material-fresh-material",
    "label": "Fresh Material Fresh Material (undefined)"
  },
  {
    "type": "light",
    "value": "glass-ui-Glass-UI-color-theme",
    "label": "Glass Ui-Glass-UI Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "gottschalg-theme-Gottschalg-Theme-color-theme",
    "label": "Gottschalg Theme-Gottschalg-Theme Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "gruvbox-concoctis-darkHard",
    "label": "Gruvbox Concoctis DarkHard (dark)"
  },
  {
    "type": "dark",
    "value": "gruvbox-concoctis-darkMedium",
    "label": "Gruvbox Concoctis DarkMedium (dark)"
  },
  {
    "type": "dark",
    "value": "gruvbox-concoctis-darkSoft",
    "label": "Gruvbox Concoctis DarkSoft (dark)"
  },
  {
    "type": "light",
    "value": "gruvbox-concoctis-lightHard",
    "label": "Gruvbox Concoctis LightHard (light)"
  },
  {
    "type": "light",
    "value": "gruvbox-concoctis-lightMedium",
    "label": "Gruvbox Concoctis LightMedium (light)"
  },
  {
    "type": "light",
    "value": "gruvbox-concoctis-lightSoft",
    "label": "Gruvbox Concoctis LightSoft (light)"
  },
  {
    "type": "dark",
    "value": "gruvbox-material-gruvbox-material-dark",
    "label": "Gruvbox Material Gruvbox Material Dark (dark)"
  },
  {
    "type": "light",
    "value": "gruvbox-material-gruvbox-material-light",
    "label": "Gruvbox Material Gruvbox Material Light (light)"
  },
  {
    "type": "dark",
    "value": "hacker-theme-hacker-color-theme",
    "label": "Hacker Theme Hacker Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "hopscotch-Hopscotch-proofreader",
    "label": "Hopscotch-Hopscotch Proofreader (dark)"
  },
  {
    "type": "dark",
    "value": "hopscotch-Hopscotch-Classic",
    "label": "Hopscotch-Hopscotch-Classic (dark)"
  },
  {
    "type": "dark",
    "value": "hopscotch-Hopscotch-Mono-proofreader",
    "label": "Hopscotch-Hopscotch-Mono Proofreader (dark)"
  },
  {
    "type": "dark",
    "value": "hopscotch-Hopscotch-Mono",
    "label": "Hopscotch-Hopscotch-Mono (dark)"
  },
  {
    "type": "dark",
    "value": "horizon-theme-vscode-horizon-bold",
    "label": "Horizon Theme Vscode Horizon Bold (dark)"
  },
  {
    "type": "light",
    "value": "horizon-theme-vscode-horizon-bright-bold",
    "label": "Horizon Theme Vscode Horizon Bright Bold (light)"
  },
  {
    "type": "light",
    "value": "horizon-theme-vscode-horizon-bright-italic",
    "label": "Horizon Theme Vscode Horizon Bright Italic (light)"
  },
  {
    "type": "light",
    "value": "horizon-theme-vscode-horizon-bright",
    "label": "Horizon Theme Vscode Horizon Bright (light)"
  },
  {
    "type": "dark",
    "value": "horizon-theme-vscode-horizon-italic",
    "label": "Horizon Theme Vscode Horizon Italic (dark)"
  },
  {
    "type": "dark",
    "value": "horizon-theme-vscode-horizon",
    "label": "Horizon Theme Vscode Horizon (dark)"
  },
  {
    "value": "hot-dog-stand-theme",
    "label": "Hot Dog Stand Theme (undefined)"
  },
  {
    "type": "dark",
    "value": "inbedby7pm-in-bed-by-7",
    "label": "Inbedby7pm In Bed By-7 (dark)"
  },
  {
    "type": "dark",
    "value": "kanagawa-kanagawa-color-theme",
    "label": "Kanagawa Kanagawa Color Theme (dark)"
  },
  {
    "value": "laravel-Laravel-color-theme",
    "label": "Laravel-Laravel Color Theme (undefined)"
  },
  {
    "type": "dark",
    "value": "light-plus-tweaked-Dark-Tweaked-color-theme",
    "label": "Light Plus Tweaked-Dark-Tweaked Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "light-plus-tweaked-Light-Tweaked-color-theme",
    "label": "Light Plus Tweaked-Light-Tweaked Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "macos-dark-mode-theme-dark-mode-mdn-theme",
    "label": "Macos Dark Mode Theme Dark Mode Mdn Theme (dark)"
  },
  {
    "type": "dark",
    "value": "macos-dark-mode-theme-dark-mode-theme",
    "label": "Macos Dark Mode Theme Dark Mode Theme (dark)"
  },
  {
    "type": "dark",
    "value": "macos-dark-mode-theme-dark-mode-warm-theme",
    "label": "Macos Dark Mode Theme Dark Mode Warm Theme (dark)"
  },
  {
    "type": "dark",
    "value": "macos-modern-theme-xcode-civic",
    "label": "Macos Modern Theme Xcode Civic (dark)"
  },
  {
    "type": "dark",
    "value": "material-dark-Material-Dark",
    "label": "Material Dark-Material-Dark (dark)"
  },
  {
    "type": "dark",
    "value": "material-palenight-theme-palenight-italic",
    "label": "Material Palenight Theme Palenight Italic (dark)"
  },
  {
    "type": "dark",
    "value": "material-palenight-theme-palenight-mild-contrast",
    "label": "Material Palenight Theme Palenight Mild Contrast (dark)"
  },
  {
    "type": "dark",
    "value": "material-palenight-theme-palenight-operator",
    "label": "Material Palenight Theme Palenight Operator (dark)"
  },
  {
    "type": "dark",
    "value": "material-palenight-theme-palenight",
    "label": "Material Palenight Theme Palenight (dark)"
  },
  {
    "type": "dark",
    "value": "Material-theme-OneDark-Pro-darker",
    "label": "Material Theme-OneDark-Pro Darker (dark)"
  },
  {
    "type": "dark",
    "value": "Material-theme-OneDark-Pro-flat",
    "label": "Material Theme-OneDark-Pro Flat (dark)"
  },
  {
    "type": "dark",
    "value": "Material-theme-OneDark-Pro-mix",
    "label": "Material Theme-OneDark-Pro Mix (dark)"
  },
  {
    "type": "dark",
    "value": "Material-theme-OneDark-Pro",
    "label": "Material Theme-OneDark-Pro (dark)"
  },
  {
    "type": "dark",
    "value": "matrix-theme-Matrix-color-theme",
    "label": "Matrix Theme-Matrix Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "mayukaithemevsc-Mayukai-midnight",
    "label": "Mayukaithemevsc-Mayukai Midnight (dark)"
  },
  {
    "type": "dark",
    "value": "mayukaithemevsc-Mayukai-mirage-color-theme-semantic",
    "label": "Mayukaithemevsc-Mayukai Mirage Color Theme Semantic (dark)"
  },
  {
    "type": "dark",
    "value": "mayukaithemevsc-Mayukai-sunset-color-theme",
    "label": "Mayukaithemevsc-Mayukai Sunset Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "merko-green-theme-merkos-green-theme-color-theme",
    "label": "Merko Green Theme Merkos Green Theme Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "midnight-synth-Midnight-Synth-color-theme",
    "label": "Midnight Synth-Midnight-Synth Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "min-theme-min-dark",
    "label": "Min Theme Min Dark (dark)"
  },
  {
    "type": "light",
    "value": "min-theme-min-light",
    "label": "Min Theme Min Light (light)"
  },
  {
    "type": "dark",
    "value": "miniprogram-vscode-extension-dark",
    "label": "Miniprogram Vscode Extension Dark (dark)"
  },
  {
    "type": "light",
    "value": "miniprogram-vscode-extension-light",
    "label": "Miniprogram Vscode Extension Light (light)"
  },
  {
    "type": "dark",
    "value": "mirage-Mirage-color-theme",
    "label": "Mirage-Mirage Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "mirage-Mirage-high-contrast-color-theme",
    "label": "Mirage-Mirage High Contrast Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "mirage-Mirage-pastel-color-theme",
    "label": "Mirage-Mirage Pastel Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "modern-purple-theme-Modern-Purple-Theme-Dark-color-theme",
    "label": "Modern Purple Theme-Modern-Purple-Theme-Dark Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "modern-purple-theme-Modern-Purple-Theme-Light-color-theme",
    "label": "Modern Purple Theme-Modern-Purple-Theme-Light Color Theme (light)"
  },
  {
    "value": "monokai-charcoal-high-contrast-Monokai-Charcoal-gray",
    "label": "Monokai Charcoal High Contrast-Monokai-Charcoal Gray (undefined)"
  },
  {
    "value": "monokai-charcoal-high-contrast-Monokai-Charcoal-green",
    "label": "Monokai Charcoal High Contrast-Monokai-Charcoal Green (undefined)"
  },
  {
    "value": "monokai-charcoal-high-contrast-Monokai-Charcoal-orange",
    "label": "Monokai Charcoal High Contrast-Monokai-Charcoal Orange (undefined)"
  },
  {
    "value": "monokai-charcoal-high-contrast-Monokai-Charcoal-purple",
    "label": "Monokai Charcoal High Contrast-Monokai-Charcoal Purple (undefined)"
  },
  {
    "value": "monokai-charcoal-high-contrast-Monokai-Charcoal-red",
    "label": "Monokai Charcoal High Contrast-Monokai-Charcoal Red (undefined)"
  },
  {
    "value": "monokai-charcoal-high-contrast-Monokai-Charcoal-white",
    "label": "Monokai Charcoal High Contrast-Monokai-Charcoal White (undefined)"
  },
  {
    "value": "monokai-charcoal-high-contrast-Monokai-Charcoal-yellow",
    "label": "Monokai Charcoal High Contrast-Monokai-Charcoal Yellow (undefined)"
  },
  {
    "value": "monokai-charcoal-high-contrast-Monokai-Charcoal",
    "label": "Monokai Charcoal High Contrast-Monokai-Charcoal (undefined)"
  },
  {
    "value": "nebula-theme-Nebula-color-theme-console",
    "label": "Nebula Theme-Nebula Color Theme Console (undefined)"
  },
  {
    "type": "light",
    "value": "netbeans-light-theme-NetBeansLight",
    "label": "Netbeans Light Theme-NetBeansLight (light)"
  },
  {
    "type": "dark",
    "value": "new-moon-vscode-new-moon",
    "label": "New Moon Vscode New Moon (dark)"
  },
  {
    "type": "dark",
    "value": "night-owl-black-Night-Owl-Black-color-theme-noitalic",
    "label": "Night Owl Black-Night-Owl-Black Color Theme Noitalic (dark)"
  },
  {
    "type": "dark",
    "value": "night-owl-black-Night-Owl-Black-color-theme",
    "label": "Night Owl Black-Night-Owl-Black Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "night-owl-Night-Owl-color-theme-noitalic",
    "label": "Night Owl-Night-Owl Color Theme Noitalic (dark)"
  },
  {
    "type": "dark",
    "value": "night-owl-Night-Owl-color-theme",
    "label": "Night Owl-Night-Owl Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "night-owl-Night-Owl-Light-color-theme-noitalic",
    "label": "Night Owl-Night-Owl-Light Color Theme Noitalic (light)"
  },
  {
    "type": "light",
    "value": "Niketa-theme-CommunicationBreakdown",
    "label": "Niketa Theme-CommunicationBreakdown (light)"
  },
  {
    "type": "light",
    "value": "Niketa-theme-DancingDays",
    "label": "Niketa Theme-DancingDays (light)"
  },
  {
    "type": "light",
    "value": "Niketa-theme-FunkyDrummer",
    "label": "Niketa Theme-FunkyDrummer (light)"
  },
  {
    "type": "light",
    "value": "Niketa-theme-GlassOnion",
    "label": "Niketa Theme-GlassOnion (light)"
  },
  {
    "type": "light",
    "value": "Niketa-theme-HelloSpaceboy",
    "label": "Niketa Theme-HelloSpaceboy (light)"
  },
  {
    "type": "light",
    "value": "Niketa-theme-KozmicBlues",
    "label": "Niketa Theme-KozmicBlues (light)"
  },
  {
    "type": "light",
    "value": "Niketa-theme-LedZeppelin",
    "label": "Niketa Theme-LedZeppelin (light)"
  },
  {
    "type": "light",
    "value": "Niketa-theme-StrangeBrew",
    "label": "Niketa Theme-StrangeBrew (light)"
  },
  {
    "type": "light",
    "value": "Niketa-theme-SweatLeaf",
    "label": "Niketa Theme-SweatLeaf (light)"
  },
  {
    "type": "dark",
    "value": "noctis-azureus",
    "label": "Noctis Azureus (dark)"
  },
  {
    "type": "dark",
    "value": "noctis-bordo",
    "label": "Noctis Bordo (dark)"
  },
  {
    "type": "light",
    "value": "noctis-hibernus",
    "label": "Noctis Hibernus (light)"
  },
  {
    "type": "dark",
    "value": "noctis-high-contrast-hc-no-italic-no-bold",
    "label": "Noctis High Contrast Hc No Italic No Bold (dark)"
  },
  {
    "type": "dark",
    "value": "noctis-high-contrast-hc-no-italic",
    "label": "Noctis High Contrast Hc No Italic (dark)"
  },
  {
    "type": "dark",
    "value": "noctis-high-contrast-hc",
    "label": "Noctis High Contrast Hc (dark)"
  },
  {
    "type": "dark",
    "value": "noctis-lilac",
    "label": "Noctis Lilac (dark)"
  },
  {
    "type": "light",
    "value": "noctis-lux",
    "label": "Noctis Lux (light)"
  },
  {
    "type": "dark",
    "value": "noctis-minimus",
    "label": "Noctis Minimus (dark)"
  },
  {
    "type": "dark",
    "value": "noctis-noctis",
    "label": "Noctis Noctis (dark)"
  },
  {
    "type": "dark",
    "value": "noctis-obscuro",
    "label": "Noctis Obscuro (dark)"
  },
  {
    "type": "dark",
    "value": "noctis-sereno",
    "label": "Noctis Sereno (dark)"
  },
  {
    "type": "dark",
    "value": "noctis-uva",
    "label": "Noctis Uva (dark)"
  },
  {
    "type": "dark",
    "value": "noctis-viola",
    "label": "Noctis Viola (dark)"
  },
  {
    "value": "Oceanic-Next-Oceanic-Next-color-theme",
    "label": "Oceanic-Next-Oceanic-Next Color Theme (undefined)"
  },
  {
    "type": "dark",
    "value": "one-dark-bimbo-one-dark-bimbo-color-theme",
    "label": "One Dark Bimbo One Dark Bimbo Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "one-dark-darker-OneDarkDarker-color-theme",
    "label": "One Dark Darker-OneDarkDarker Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "one-dark-pro-monokai-darker-OneDarkProMonokaiDarker-color-theme",
    "label": "One Dark Pro Monokai Darker-OneDarkProMonokaiDarker Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "One-dark-pro-OneDark-Pro-flat",
    "label": "One Dark Pro-OneDark-Pro Flat (dark)"
  },
  {
    "type": "dark",
    "value": "One-dark-pro-OneDark-Pro",
    "label": "One Dark Pro-OneDark-Pro (dark)"
  },
  {
    "type": "dark",
    "value": "one-monokai-OneMonokai-color-theme",
    "label": "One Monokai-OneMonokai Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "origamid-next-origamid-next-color-theme",
    "label": "Origamid Next Origamid Next Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "origamid-theme-origamid",
    "label": "Origamid Theme Origamid (dark)"
  },
  {
    "type": "dark",
    "value": "overnight-Overnight-color-theme-italic",
    "label": "Overnight-Overnight Color Theme Italic (dark)"
  },
  {
    "type": "dark",
    "value": "overnight-Overnight-color-theme",
    "label": "Overnight-Overnight Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "overnight-Overnight-Slumber-italic",
    "label": "Overnight-Overnight-Slumber Italic (dark)"
  },
  {
    "type": "dark",
    "value": "overnight-Overnight-Slumber",
    "label": "Overnight-Overnight-Slumber (dark)"
  },
  {
    "type": "dark",
    "value": "popping-and-locking-vscode-black-popping-and-locking-black",
    "label": "Popping And Locking Vscode Black Popping And Locking Black (dark)"
  },
  {
    "type": "dark",
    "value": "popping-and-locking-vscode-popping-and-locking-color-theme",
    "label": "Popping And Locking Vscode Popping And Locking Color Theme (dark)"
  },
  {
    "value": "PowerShell-Preview-theme",
    "label": "PowerShell-Preview Theme (undefined)"
  },
  {
    "value": "PowerShell-theme",
    "label": "PowerShell Theme (undefined)"
  },
  {
    "type": "light",
    "value": "py-light-Py-Light-color-theme",
    "label": "Py Light-Py-Light Color Theme (light)"
  },
  {
    "value": "radical-vscode-Radical",
    "label": "Radical Vscode-Radical (undefined)"
  },
  {
    "type": "dark",
    "value": "relaxed-theme-relaxed-color-theme",
    "label": "Relaxed Theme Relaxed Color Theme (dark)"
  },
  {
    "value": "reloaded-themes-reloaded-dark-darker",
    "label": "Reloaded Themes Reloaded Dark Darker (undefined)"
  },
  {
    "value": "reloaded-themes-reloaded-dark-hc",
    "label": "Reloaded Themes Reloaded Dark Hc (undefined)"
  },
  {
    "type": "dark",
    "value": "reui-reui-2-dark-italic",
    "label": "Reui Reui-2 Dark Italic (dark)"
  },
  {
    "type": "dark",
    "value": "reui-reui-2-dark",
    "label": "Reui Reui-2 Dark (dark)"
  },
  {
    "type": "dark",
    "value": "reui-reui-2-italic",
    "label": "Reui Reui-2 Italic (dark)"
  },
  {
    "type": "dark",
    "value": "reui-reui-2-mirage-italic",
    "label": "Reui Reui-2 Mirage Italic (dark)"
  },
  {
    "type": "dark",
    "value": "reui-reui-2-mirage",
    "label": "Reui Reui-2 Mirage (dark)"
  },
  {
    "type": "dark",
    "value": "reui-reui-2",
    "label": "Reui Reui-2 (dark)"
  },
  {
    "type": "dark",
    "value": "reui-reui-italic",
    "label": "Reui Reui Italic (dark)"
  },
  {
    "type": "dark",
    "value": "reui-reui-mirage-italic",
    "label": "Reui Reui Mirage Italic (dark)"
  },
  {
    "type": "dark",
    "value": "reui-reui-mirage",
    "label": "Reui Reui Mirage (dark)"
  },
  {
    "type": "dark",
    "value": "reui-reui",
    "label": "Reui Reui (dark)"
  },
  {
    "value": "sandstorm-sandstorm-classic-color-theme",
    "label": "Sandstorm Sandstorm Classic Color Theme (undefined)"
  },
  {
    "value": "sandstorm-sandstorm-darker-color-theme",
    "label": "Sandstorm Sandstorm Darker Color Theme (undefined)"
  },
  {
    "type": "dark",
    "value": "simple-dark-dark-soft",
    "label": "Simple Dark Dark Soft (dark)"
  },
  {
    "type": "dark",
    "value": "simple-dark-dark",
    "label": "Simple Dark Dark (dark)"
  },
  {
    "type": "dark",
    "value": "slack-theme-aubergine-dark",
    "label": "Slack Theme Aubergine Dark (dark)"
  },
  {
    "type": "dark",
    "value": "slack-theme-aubergine-new",
    "label": "Slack Theme Aubergine New (dark)"
  },
  {
    "type": "dark",
    "value": "slack-theme-aubergine",
    "label": "Slack Theme Aubergine (dark)"
  },
  {
    "type": "dark",
    "value": "slack-theme-choco-mint",
    "label": "Slack Theme Choco Mint (dark)"
  },
  {
    "type": "light",
    "value": "slack-theme-hoth",
    "label": "Slack Theme Hoth (light)"
  },
  {
    "type": "dark",
    "value": "slack-theme-monument",
    "label": "Slack Theme Monument (dark)"
  },
  {
    "type": "dark",
    "value": "slack-theme-ochin",
    "label": "Slack Theme Ochin (dark)"
  },
  {
    "type": "dark",
    "value": "slack-theme-protanopia-deuteranopia",
    "label": "Slack Theme Protanopia Deuteranopia (dark)"
  },
  {
    "type": "dark",
    "value": "slack-theme-tritanopia",
    "label": "Slack Theme Tritanopia (dark)"
  },
  {
    "type": "dark",
    "value": "slack-theme-work-hard",
    "label": "Slack Theme Work Hard (dark)"
  },
  {
    "type": "dark",
    "value": "slime-slime-color-theme",
    "label": "Slime Slime Color Theme (dark)"
  },
  {
    "value": "spotify-color-theme-spotify-soft",
    "label": "Spotify Color Theme Spotify Soft (undefined)"
  },
  {
    "value": "spotify-color-theme-spotify",
    "label": "Spotify Color Theme Spotify (undefined)"
  },
  {
    "type": "dark",
    "value": "sublime-mavensmate-monokai-apex-Sublime-MavensMate-Monokai-color-theme-Dimmed",
    "label": "Sublime Mavensmate Monokai Apex-Sublime-MavensMate-Monokai Color Theme-Dimmed (dark)"
  },
  {
    "type": "dark",
    "value": "sublime-mavensmate-monokai-apex-Sublime-MavensMate-Monokai-color-theme",
    "label": "Sublime Mavensmate Monokai Apex-Sublime-MavensMate-Monokai Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "sublime-vscode-theme-sublime-vscode-theme",
    "label": "Sublime Vscode Theme Sublime Vscode Theme (dark)"
  },
  {
    "type": "dark",
    "value": "sunset-theme-sunset-theme",
    "label": "Sunset Theme Sunset Theme (dark)"
  },
  {
    "type": "dark",
    "value": "sweetdracula-sweetdracula-color-theme",
    "label": "Sweetdracula Sweetdracula Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "syntax-Syntax-Dark-color-theme",
    "label": "Syntax-Syntax-Dark Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "syntax-Syntax-Light-color-theme",
    "label": "Syntax-Syntax-Light Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "synthwave-x-fluoromachine-synthwave-x-fluoromachine",
    "label": "Synthwave X Fluoromachine Synthwave X Fluoromachine (dark)"
  },
  {
    "value": "theme-alabaster-alabaster-color-theme",
    "label": "Theme Alabaster Alabaster Color Theme (undefined)"
  },
  {
    "value": "theme-bluloco-dark-bluloco-dark-color-theme",
    "label": "Theme Bluloco Dark Bluloco Dark Color Theme (undefined)"
  },
  {
    "value": "theme-bluloco-dark-bluloco-dark-italic-color-theme",
    "label": "Theme Bluloco Dark Bluloco Dark Italic Color Theme (undefined)"
  },
  {
    "type": "light",
    "value": "theme-bluloco-light-bluloco-light-color-theme",
    "label": "Theme Bluloco Light Bluloco Light Color Theme (light)"
  },
  {
    "value": "theme-bluloco-light-bluloco-light-italic-color-theme",
    "label": "Theme Bluloco Light Bluloco Light Italic Color Theme (undefined)"
  },
  {
    "type": "dark",
    "value": "theme-gotham-gotham",
    "label": "Theme Gotham Gotham (dark)"
  },
  {
    "type": "dark",
    "value": "theme-kay-Dark",
    "label": "Theme Kay-Dark (dark)"
  },
  {
    "type": "light",
    "value": "theme-kay-Light",
    "label": "Theme Kay-Light (light)"
  },
  {
    "type": "dark",
    "value": "theme-launchbase-launchbase",
    "label": "Theme Launchbase Launchbase (dark)"
  },
  {
    "type": "dark",
    "value": "theme-macos-classic-macOS-classic-dark",
    "label": "Theme Macos Classic MacOS Classic Dark (dark)"
  },
  {
    "type": "light",
    "value": "theme-macos-classic-macOS-classic",
    "label": "Theme Macos Classic MacOS Classic (light)"
  },
  {
    "type": "dark",
    "value": "theme-material-dark-soda-Material-Dark-Soda-color-theme",
    "label": "Theme Material Dark Soda-Material-Dark-Soda Color Theme (dark)"
  },
  {
    "value": "theme-obsidian-son-of-obsidian-color-theme",
    "label": "Theme Obsidian Son Of Obsidian Color Theme (undefined)"
  },
  {
    "value": "theme-onedark-OneDarkTheme-color-theme",
    "label": "Theme Onedark-OneDarkTheme Color Theme (undefined)"
  },
  {
    "value": "theme-panda-Panda",
    "label": "Theme Panda-Panda (undefined)"
  },
  {
    "type": "dark",
    "value": "theme-pink-cat-boo-pink-cat-boo",
    "label": "Theme Pink Cat Boo Pink Cat Boo (dark)"
  },
  {
    "value": "theme-quietlight-vsc-QuietLight",
    "label": "Theme Quietlight Vsc-QuietLight (undefined)"
  },
  {
    "value": "theme-sapphire-theme-bright",
    "label": "Theme Sapphire Theme Bright (undefined)"
  },
  {
    "value": "theme-sapphire-theme-dim",
    "label": "Theme Sapphire Theme Dim (undefined)"
  },
  {
    "value": "theme-sapphire-theme",
    "label": "Theme Sapphire Theme (undefined)"
  },
  {
    "type": "dark",
    "value": "vsc-community-material-theme-Community-Material-Theme-Darker-High-Contrast",
    "label": "Vsc Community Material Theme-Community-Material-Theme-Darker-High-Contrast (dark)"
  },
  {
    "type": "dark",
    "value": "vsc-community-material-theme-Community-Material-Theme-Darker",
    "label": "Vsc Community Material Theme-Community-Material-Theme-Darker (dark)"
  },
  {
    "type": "dark",
    "value": "vsc-community-material-theme-Community-Material-Theme-Default-High-Contrast",
    "label": "Vsc Community Material Theme-Community-Material-Theme-Default-High-Contrast (dark)"
  },
  {
    "type": "dark",
    "value": "vsc-community-material-theme-Community-Material-Theme-Default",
    "label": "Vsc Community Material Theme-Community-Material-Theme-Default (dark)"
  },
  {
    "type": "light",
    "value": "vsc-community-material-theme-Community-Material-Theme-Lighter-High-Contrast",
    "label": "Vsc Community Material Theme-Community-Material-Theme-Lighter-High-Contrast (light)"
  },
  {
    "type": "light",
    "value": "vsc-community-material-theme-Community-Material-Theme-Lighter",
    "label": "Vsc Community Material Theme-Community-Material-Theme-Lighter (light)"
  },
  {
    "type": "dark",
    "value": "vsc-community-material-theme-Community-Material-Theme-Ocean-High-Contrast",
    "label": "Vsc Community Material Theme-Community-Material-Theme-Ocean-High-Contrast (dark)"
  },
  {
    "type": "dark",
    "value": "vsc-community-material-theme-Community-Material-Theme-Ocean",
    "label": "Vsc Community Material Theme-Community-Material-Theme-Ocean (dark)"
  },
  {
    "type": "dark",
    "value": "vsc-community-material-theme-Community-Material-Theme-Palenight-High-Contrast",
    "label": "Vsc Community Material Theme-Community-Material-Theme-Palenight-High-Contrast (dark)"
  },
  {
    "type": "dark",
    "value": "vsc-community-material-theme-Community-Material-Theme-Palenight",
    "label": "Vsc Community Material Theme-Community-Material-Theme-Palenight (dark)"
  },
  {
    "type": "dark",
    "value": "vscode-chester-atom-vscodechesteratom",
    "label": "Vscode Chester Atom Vscodechesteratom (dark)"
  },
  {
    "type": "dark",
    "value": "vscode-field-lights-Field-Lights-color-theme",
    "label": "Vscode Field Lights-Field-Lights Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "vscode-hipster-theme-Hipster-color-theme",
    "label": "Vscode Hipster Theme-Hipster Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "vscode-office-OneDark-Modern",
    "label": "Vscode Office-OneDark-Modern (dark)"
  },
  {
    "value": "vscode-snazzy-operator-snazzy-operator-color-theme",
    "label": "Vscode Snazzy Operator Snazzy Operator Color Theme (undefined)"
  },
  {
    "value": "vscode-solidity-language-OneDarkAuditor",
    "label": "Vscode Solidity Language-OneDarkAuditor (undefined)"
  },
  {
    "type": "dark",
    "value": "vscode-theme-1984-1984-color-theme",
    "label": "Vscode Theme-1984-1984 Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "vscode-theme-1984-1984-cyberpunk-color-theme",
    "label": "Vscode Theme-1984-1984 Cyberpunk Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "vscode-theme-1984-1984-fancy-color-theme",
    "label": "Vscode Theme-1984-1984 Fancy Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "vscode-theme-1984-1984-unbolded-color-theme",
    "label": "Vscode Theme-1984-1984 Unbolded Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "vscode-theme-darcula-darcula",
    "label": "Vscode Theme Darcula Darcula (dark)"
  },
  {
    "type": "light",
    "value": "vscode-theme-django-django",
    "label": "Vscode Theme Django Django (light)"
  },
  {
    "type": "light",
    "value": "vscode-theme-django-jupyter",
    "label": "Vscode Theme Django Jupyter (light)"
  },
  {
    "value": "vscode-theme-onedark-OneDark",
    "label": "Vscode Theme Onedark-OneDark (undefined)"
  },
  {
    "value": "vscode-theme-onedark-spacegray-OneDark",
    "label": "Vscode Theme Onedark Spacegray-OneDark (undefined)"
  },
  {
    "value": "vscode-theme-onelight-OneLight",
    "label": "Vscode Theme Onelight-OneLight (undefined)"
  },
  {
    "type": "dark",
    "value": "webstorm-intellij-darcula-theme-darcula-color-theme",
    "label": "Webstorm Intellij Darcula Theme Darcula Color Theme (dark)"
  },
  {
    "value": "white-White-color-theme",
    "label": "White-White Color Theme (undefined)"
  },
  {
    "value": "white-White-Night-color-theme",
    "label": "White-White-Night Color Theme (undefined)"
  },
  {
    "type": "dark",
    "value": "winteriscoming-WinterIsComing-dark-blue-color-no-italics-theme",
    "label": "Winteriscoming-WinterIsComing Dark Blue Color No Italics Theme (dark)"
  },
  {
    "type": "dark",
    "value": "winteriscoming-WinterIsComing-dark-blue-color-theme",
    "label": "Winteriscoming-WinterIsComing Dark Blue Color Theme (dark)"
  },
  {
    "type": "dark",
    "value": "winteriscoming-WinterIsComing-dark-color-no-italics-theme",
    "label": "Winteriscoming-WinterIsComing Dark Color No Italics Theme (dark)"
  },
  {
    "type": "dark",
    "value": "winteriscoming-WinterIsComing-dark-color-theme",
    "label": "Winteriscoming-WinterIsComing Dark Color Theme (dark)"
  },
  {
    "type": "light",
    "value": "winteriscoming-WinterIsComing-light-color-no-italics-theme",
    "label": "Winteriscoming-WinterIsComing Light Color No Italics Theme (light)"
  },
  {
    "type": "light",
    "value": "winteriscoming-WinterIsComing-light-color-theme",
    "label": "Winteriscoming-WinterIsComing Light Color Theme (light)"
  },
  {
    "type": "dark",
    "value": "wvsc-serendipity-serendipity-midnight",
    "label": "Wvsc Serendipity Serendipity Midnight (dark)"
  },
  {
    "type": "light",
    "value": "wvsc-serendipity-serendipity-morning",
    "label": "Wvsc Serendipity Serendipity Morning (light)"
  },
  {
    "type": "dark",
    "value": "wvsc-serendipity-serendipity-sunset",
    "label": "Wvsc Serendipity Serendipity Sunset (dark)"
  },
  {
    "type": "dark",
    "value": "xcode-12-theme-Xcode-Classic-Dark",
    "label": "Xcode-12 Theme-Xcode-Classic-Dark (dark)"
  },
  {
    "type": "light",
    "value": "xcode-12-theme-Xcode-Classic-Light",
    "label": "Xcode-12 Theme-Xcode-Classic-Light (light)"
  },
  {
    "type": "dark",
    "value": "xcode-12-theme-Xcode-Default-Dark-Customized-Version",
    "label": "Xcode-12 Theme-Xcode-Default-Dark-Customized-Version (dark)"
  },
  {
    "type": "dark",
    "value": "xcode-12-theme-Xcode-Default-Dark",
    "label": "Xcode-12 Theme-Xcode-Default-Dark (dark)"
  }
];