export const LanguageOptions = [
  {
    value: ".generic",
    label: "Generic",
    extensions: ".*",
    mode: "",
  },
  {
    value: ".s",
    label: "Assembly",
    extensions: ".s",
    mode: "assembly_x86",
  },
  {
    value: ".sh",
    label: "Bash",
    extensions: ".sh",
    mode: "sh",
  },
  {
    value: ".c",
    label: "C/C++",
    extensions: ".c,.h,.cpp",
    mode: "c_cpp",
  },
  {
    value: ".cs",
    label: "C#",
    extensions: ".cs",
    mode: "csharp",
  },
  {
    value: ".clj",
    label: "Clojure",
    extensions: ".clj",
    mode: "clojure",
  },
  {
    value: ".css",
    label: "CSS",
    extensions: ".css,.scss",
    mode: "css",
  },
  {
    value: ".dart",
    label: "Dart",
    extensions: ".dart",
    mode: "dart",
  },
  {
    value: ".elm",
    label: "Elm",
    extensions: ".elm",
    mode: "elm",
  },
  {
    value: ".erl",
    label: "Erlang",
    extensions: ".erl",
    mode: "erlang",
  },
  {
    value: ".ex",
    label: "Elixir",
    extensions: ".ex",
    mode: "elixir",
  },
  {
    value: ".html",
    label: "HTML/XML",
    extensions: ".html,.xml",
    mode: "html",
  },
  {
    value: ".hs",
    label: "Haskell",
    extensions: ".hs",
    mode: "haskell",
  },
  {
    value: ".go",
    label: "Go",
    extensions: ".go",
    mode: "golang",
  },
  {
    value: ".java",
    label: "Java",
    extensions: ".java",
    mode: "java",
  },
  {
    value: ".js",
    label: "JS/Typescript",
    extensions: ".js,.ts,.jsx,.tsx",
    mode: "typescript",
  },
  {
    value: ".json",
    label: "JSON",
    extensions: ".json",
    mode: "json",
  },
  {
    value: ".jl",
    label: "Julia",
    extensions: ".jl",
    mode: "julia",
  },
  {
    value: ".tex",
    label: "Latex",
    extensions: ".tex",
    mode: "latex",
  },
  {
    value: ".ml",
    label: "OCaml",
    extensions: ".ml",
    mode: "ocaml",
  },
  {
    value: ".php",
    label: "PHP",
    extensions: ".php",
    mode: "php",
  },
  {
    value: ".py",
    label: "Python",
    extensions: ".py",
    mode: "python",
  },
  {
    value: ".re",
    label: "Reason",
    extensions: ".re",
    mode: "ocaml",
  },
  {
    value: ".rb",
    label: "Ruby",
    extensions: ".rb",
    mode: "ruby",
  },
  {
    value: ".rs",
    label: "Rust",
    extensions: ".rs",
    mode: "rust",
  },
  {
    value: ".scala",
    label: "Scala",
    extensions: ".scala",
    mode: "scala",
  },
  {
    value: ".sql",
    label: "SQL",
    extensions: ".sql",
    mode: "sql",
  },
  {
    value: ".swift",
    label: "Swift",
    extensions: ".swift",
    mode: "swift",
  },
  {
    value: ".xml",
    label: "XML",
    extensions: ".xml",
    mode: "xml",
  },
  {
    value: ".txt",
    label: "Text",
    extensions: ".txt",
    mode: "",
  },
];
